name: PreKick
version: 2.0
description: A whitelist plugin for bukkit with custom kick messages.
author: WildN00b
authors: [WildN00b] 
website: http://forums.bukkit.org/threads/admin-prekick-v0-7-1-whitelist-with-custom-messages-953.15507/
main: me.wildn00b.prekick.PreKick
softdepend: [Vault]

commands:
  prekick:
    description: The control panel for PreKick
    aliases: [pk]
    permission: prekick.show
    usage: Syntax error! Simply type /<command> to access the PreKick control panel.
    
permissions:
  prekick.*:
    description: All PreKick permissions
    default: op
    children:
      prekick.show: true
      prekick.seekick: true
      prekick.switch: true
      prekick.whitelistswitch: true
      prekick.ipswitch: true
      prekick.add: true
      prekick.remove: true
      prekick.addip: true
      prekick.removeip: true
  prekick.show:
    description: Allows to show the menu
    default: false
  prekick.seekick:
    description: Allows to see when someone was kicked
    default: false
  prekick.switch:
    description: Allows you to turn on and off prekick
    default: false
  prekick.whitelistswitch:
    description: Allows you to turn on and off the whitelist
    default: false
  prekick.ipswitch:
    description: Allows you to turn on and off the iplist
    default: false
  prekick.add:
    description: Allows you to add users to the whitelist
    default: false
  prekick.remove:
    description: Allows you to remove users from the whitelist
    default: false
  prekick.addip:
    description: Allows you to add users to the iplist
    default: false
  prekick.removeip:
    description: Allows you to remove users for the iplist
    default: false